### ISSUE TITLE
Red Error Messages in Log

### ISSUE THREAD

**Issue by colinrblake** [joeyhage/homebridge-alexa-smarthome#160]
**Describe The Bug:**

I upgraded from 2.2.0 Alpha 5 to the released 2.2.0 and now I'm getting lots of red messages in my Homebridge status log (I don't think I had these before). However, the lights in question DO operate correctly from the Home app.

**To Reproduce:**

Nothing special to reproduce. As soon as I restart Homebridge the errors appear.

**Expected behavior:**

No error messages.

**Logs:**

```
[7/25/2024, 1:18:01 PM] [HomebridgeAlexaSmartHome] Patio Light 1 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:01 PM] [HomebridgeAlexaSmartHome] Porch Light 2 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:01 PM] [HomebridgeAlexaSmartHome] Patio Light 1 - Get hue - InvalidResponse(State not available)
[7/25/2024, 1:18:01 PM] [HomebridgeAlexaSmartHome] Porch Light 2 - Get hue - InvalidResponse(State not available)
[7/25/2024, 1:18:02 PM] [HomebridgeAlexaSmartHome] Patio Light 2 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:02 PM] [HomebridgeAlexaSmartHome] Patio Light 2 - Get hue - InvalidResponse(State not available)
[7/25/2024, 1:18:03 PM] [HomebridgeAlexaSmartHome] Porch Light 3 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:03 PM] [HomebridgeAlexaSmartHome] Porch Light 3 - Get hue - InvalidResponse(State not available)
[7/25/2024, 1:18:03 PM] [HomebridgeAlexaSmartHome] Patio Light 3 - Get hue - InvalidResponse(State not available)
[7/25/2024, 1:18:03 PM] [HomebridgeAlexaSmartHome] Patio Light 3 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:04 PM] [HomebridgeAlexaSmartHome] Porch Light 1 - Get saturation - InvalidResponse(State not available)
[7/25/2024, 1:18:04 PM] [HomebridgeAlexaSmartHome] Porch Light 1 - Get hue - InvalidResponse(State not available)
```

**Plugin Config:**

```json
{
    "devices": [
        "Porch Light 1",
        "Porch Light 2",
        "Porch Light 3",
        "Patio Light 1",
        "Patio Light 2",
        "Patio Light 3",
        "Porch Lights Switch",
        "Patio Light Switch"
    ],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "colins-mac-mini.local",
            "port": 8987
        }
    },
    "amazonDomain": "amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 300,
        "backgroundRefresh": true
    },
    "debug": false,
    "platform": "HomebridgeAlexaSmartHome"
}
```

**Screenshots:**

N/A

**Environment:**

- **Plugin Version**: 2.2.0 (released version)
- **Homebridge Version**: 1.8.4
- **Node.js Version**:  v20.15.0
- **NPM Version**: 10.7.0 
- **Operating System**: macOS 14.5

**Comment by joeyhage** [comment]
@colinrblake This seems like an issue with the Alexa skill that links these lights. What is the manufacturer of these lights and what Alexa skill are they linked through?

**Comment by winstonstwn** [comment]
I'm also having this issue, and it seems to affect every device included. I mostly used all hue lights and it still manage to control properly albeit the errors in log. However, the broadlink ac control that I linked now gives "no response" :\

![image](https://github.com/user-attachments/assets/ca019471-e31f-4a26-81cf-df6263e3a6b0)

**Comment by colinrblake** [comment]
@joeyhage These are Sylvania lights and I linked them to Alexa via the Sylvania app on my iPhone. On Alexa I have the "Sylvania Smart Wifi" skill.

**Comment by SheldorSheldonDZ** [comment]
@joeyhage I have the same issue with all of my lights. When using the newest version (v2.2.1) I get this message for all of my lights. Those lights are connect through different skills in Alexa and they are not all from the same manufacture. Downgrading to v.2.1.5 helped me to "fix" it for now.

**Comment by Aekung** [comment]
Confirmed the issue. Temporary fixed with @SheldorSheldonDZ method by downgrading to v2.1.5.

**Comment by SheldorSheldonDZ** [comment]
@joeyhage I now upgraded to the newest version v2.2.1 for preparing to homebridge v2. Now in v2.2.1 all my lights are working again but I still get "Get color temperature - InvalidResponse(State not available)" or "Get brightness - InvalidResponse(State not available)" in the log. Funny is that I CAN change color and brightness in the home app and it adopts to the lights but the home app stays on the "old" values and shows that the hardware is not responding even though it works..... It's now an very annoying bug since July - any way to fix this?

**Comment by darkaeden** [comment]
> @joeyhage I now upgraded to the newest version v2.2.1 for preparing to homebridge v2. Now in v2.2.1 all my lights are working again but I still get "Get color temperature - InvalidResponse(State not available)" or "Get brightness - InvalidResponse(State not available)" in the log. Funny is that I CAN change color and brightness in the home app and it adopts to the lights but the home app stays on the "old" values and shows that the hardware is not responding even though it works..... It's now an very annoying bug since July - any way to fix this?

Same here. All color bulbs shows as No Response in Apple Home. But, if i click and increase the slider it turn on the light to the desidered light level...

**Comment by joannadal** [comment]
I thinks that issue is the same: https://github.com/joeyhage/homebridge-alexa-smarthome/issues/227

Could anyone confirm that on the version v.2.1.5 it works? Thanks!
