### ISSUE TITLE
Air quality sensor Service communication error

### ISSUE THREAD

**Issue by saveriospeziali** [joeyhage/homebridge-alexa-smarthome#178]
Hi, just installed the plugin, my main interest is to access Amazon Air Quality sensor data but I always get "Service communication error" and "InvalidResponse(State not available)", can someone help?

Thank's in advance

[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria humidity - Get humidity - InvalidResponse(State not available)
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria humidity - Service communication error
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Service communication error
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Get air quality - InvalidResponse(State not available)
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Obtained device state from cache
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Obtained device state from cache
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Get PM2.5 density - InvalidResponse(State not available)
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Service communication error
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Get VOC density - InvalidResponse(State not available)
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria - Service communication error
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Obtained device state from cache
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Obtained device state from cache
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria carbon monoxide - Get carbon monoxide detected - InvalidResponse(State not available)
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria carbon monoxide - Service communication error
[9/28/2024, 7:53:29 PM] [HomebridgeAlexaSmartHome] Qualità dell'aria carbon monoxide - Get carbon monoxide level - InvalidResponse(State not avai

**Comment by saveriospeziali** [comment]
Hi
Fixed downgrading to v2.1.5

**Comment by dltacube** [comment]
Just wanted to write some notes in case this issue is related to last year's rate limiting of air quality monitors. The issue was fixed by 2.2.0 here: https://github.com/joeyhage/homebridge-alexa-smarthome/issues/58 which is strange because now we're saying to downgrade by just 1 version.

I mentioned in discord but should have said it here too but queries to air quality monitors take 20+ seconds when we also ask the graph api for "relationships" and removing that reduces response time down to 400ms. Do we know if that is happening with 2.2.0? If not I'd be willing to run some print statements or a proxy but since it's very time consuming I thought I'd ask first.

**Comment by saveriospeziali** [comment]
> Just wanted to write some notes in case this issue is related to last year's rate limiting of air quality monitors. The issue was fixed by 2.2.0 here: #58 which is strange because now we're saying to downgrade by just 1 version.
> 
> I mentioned in discord but should have said it here too but queries to air quality monitors take 20+ seconds when we also ask the graph api for "relationships" and removing that reduces response time down to 400ms. Do we know if that is happening with 2.2.0? If not I'd be willing to run some print statements or a proxy but since it's very time consuming I thought I'd ask first.
> 
> [v2.1.5...v2.2.0](https://github.com/joeyhage/homebridge-alexa-smarthome/compare/v2.1.5...v2.2.0)

Dear dltacube

I confirm the issue was with version 2.2.1
I just installed 2.2.0 but the issue is still there.. going back to 2.1.5


Let me know if I can help 
Regard
